"""One-click deployment engine for Streamlit / Gradio bundles.

Drivers:
  local_process - run the app as a child process on an allocated port (default; great for demos)
  coolify       - create/deploy an application through the Coolify API
  manifest      - only generate Dockerfile + compose, no execution (air-gapped review)

Every bundle gets a generated Dockerfile so the exact same artifact can be
handed to Coolify, Fly, Render or plain `docker run`.
"""
from __future__ import annotations

import os
import re
import shutil
import signal
import socket
import subprocess
import sys
import time
import zipfile
from datetime import datetime, timezone
from pathlib import Path

import httpx
from sqlmodel import Session, select

from app.core.config import settings
from app.domain.enums import AppFramework, DeploymentStatus
from app.domain.models import Deployment

DOCKERFILE_TEMPLATE = """# Generated by ATLAS one-click deploy
FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential curl libglib2.0-0 libsm6 libxext6 libxrender1 \\
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r /app/requirements.txt

COPY . /app

EXPOSE {port}
HEALTHCHECK --interval=30s --timeout=5s --start-period=40s --retries=3 \\
  CMD curl -fsS http://localhost:{port}{health} || exit 1

CMD {cmd}
"""

# Every app is served under a base URL path on the main domain (a virtual
# directory) rather than its own public port, so a whole cohort shares one
# domain behind a single reverse proxy. Streamlit uses server.baseUrlPath;
# Gradio uses the GRADIO_ROOT_PATH env var. The base path is e.g. "app/app1"
# (no leading slash).
STREAMLIT_CMD = ('["streamlit", "run", "{entry}", "--server.port={port}", '
                 '"--server.address=0.0.0.0", "--server.baseUrlPath={base_path}", '
                 '"--server.headless=true", "--browser.gatherUsageStats=false"]')
GRADIO_CMD = '["python", "{entry}"]'
GRADIO_ROOT_PATH_ENV = "GRADIO_ROOT_PATH"

NGINX_HEADER = """# ATLAS reverse-proxy config for deployed apps
#
# Every app runs on an internal port and is served under a path on the main
# domain - https://<domain>/app/<slug> - so the cohort needs only ONE public
# domain/port (80/443) and a single nginx. Drop the <location> blocks below
# into your server{{}} block and reload nginx.
#
# Generated: {generated}
"""

NGINX_FOOTER = """# You can also generate this on demand from the UI:
#   Portal -> "Proxy config"
# or fetch it directly:
#   GET /api/deployments/proxy-config  (Bearer token, admin/supervisor)
"""

BASE_REQS = {
    AppFramework.STREAMLIT: "streamlit>=1.36\npandas>=2.0\nnumpy>=1.26\nscikit-learn>=1.4\nopenpyxl>=3.1\nplotly>=5.20\n",
    AppFramework.GRADIO: "gradio>=4.44\npandas>=2.0\nnumpy>=1.26\nscikit-learn>=1.4\nopenpyxl>=3.1\nplotly>=5.20\n",
}


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug[:48] or "app"


def unpack_bundle(deployment: Deployment, data: bytes, filename: str) -> Path:
    root = settings.storage_dir / "deployments" / f"{deployment.id}_{deployment.slug}"
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True, exist_ok=True)
    if filename.lower().endswith(".zip"):
        tmp = root / "_bundle.zip"
        tmp.write_bytes(data)
        with zipfile.ZipFile(tmp) as zf:
            for member in zf.namelist():
                if member.startswith("/") or ".." in member:
                    continue
                zf.extract(member, root)
        tmp.unlink(missing_ok=True)
        entries = [p for p in root.iterdir() if not p.name.startswith("_")]
        if len(entries) == 1 and entries[0].is_dir():
            inner = entries[0]
            for item in inner.iterdir():
                shutil.move(str(item), str(root / item.name))
            inner.rmdir()
    else:
        (root / filename).write_bytes(data)
    return root


def base_url_path(slug: str) -> str:
    """The virtual-directory path segment for an app, e.g. "app/my-app"."""
    prefix = (settings.deploy_url_prefix or "app").strip("/")
    return f"{prefix}/{slug}".strip("/")


def ensure_scaffold(root: Path, framework: AppFramework, entrypoint: str,
                    port: int, base_path: str) -> str:
    """Guarantee requirements.txt + Dockerfile exist. Returns the Dockerfile text."""
    reqs = root / "requirements.txt"
    if not reqs.exists():
        reqs.write_text(BASE_REQS[framework])
    else:
        text = reqs.read_text()
        pkg = "streamlit" if framework == AppFramework.STREAMLIT else "gradio"
        if pkg not in text:
            reqs.write_text(text.rstrip() + "\n" + BASE_REQS[framework])

    if framework == AppFramework.STREAMLIT:
        cmd = STREAMLIT_CMD.format(entry=entrypoint, port=port, base_path=base_path)
        health = f"/{base_path}/_stcore/health"
    else:
        cmd = GRADIO_CMD.format(entry=entrypoint)
        health = f"/{base_path}/"
    dockerfile = DOCKERFILE_TEMPLATE.format(port=port, cmd=cmd, health=health)
    (root / "Dockerfile").write_text(dockerfile)

    (root / ".dockerignore").write_text("__pycache__/\n*.pyc\n.venv/\n.git/\n*.zip\n")
    # The app listens on the main domain under /app/<slug> (no public port), so
    # the compose file maps nothing externally. If you do expose a port, the
    # path below is still what the app is served under.
    root_path_env = ""
    if framework == AppFramework.GRADIO:
        root_path_env = f"      - {GRADIO_ROOT_PATH_ENV}=/{base_path}\n"
    compose = f"""services:
  app:
    build: .
    # no host port: the app is served under /{base_path} via the nginx proxy.
{root_path_env}    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT={port}
    restart: unless-stopped
"""
    (root / "docker-compose.yml").write_text(compose)
    return dockerfile


def _allocate_port(session: Session) -> int:
    used = {d.internal_port for d in session.exec(select(Deployment)) if d.internal_port}
    for port in range(settings.deploy_port_start, settings.deploy_port_end + 1):
        if port not in used:
            return port
    raise RuntimeError("No free deployment port available.")


def _public_url(port: int, slug: str) -> str:
    """Public URL for a deployed app: a virtual directory on the main domain.

    The app is NOT a separate port/service - it lives under /app/<slug>/ on the
    main domain and nginx routes that path to the internal port. The trailing
    slash is deliberate: the proxy `location /app/<slug>/` only matches with it.
    In the sandbox preview (e2b) the environment is port-addressed, so the path
    is appended to the per-port subdomain instead.
    """
    path = base_url_path(slug)
    base = settings.public_base_url
    if base and ".e2b.app" in base:
        host = base.split("://", 1)[-1]
        parts = host.split("-", 1)
        if len(parts) == 2:
            return f"https://{port}-{parts[1]}/{path}/"
    if base:
        return f"{base.rstrip('/')}/{path}/"
    return f"http://localhost:{port}/{path}/"


def running_routes(session: Session) -> list[dict]:
    """Running deployments with everything nginx needs to route their paths."""
    rows = session.exec(select(Deployment).where(
        Deployment.status == DeploymentStatus.RUNNING)).all()
    out = []
    for d in rows:
        if not d.internal_port:
            continue
        out.append({
            "slug": d.slug,
            "name": d.name,
            "framework": d.framework.value,
            "port": d.internal_port,
            "path": base_url_path(d.slug),
            "url": d.url or "",
        })
    return sorted(out, key=lambda r: r["path"])


def nginx_conf(routes: list[dict]) -> str:
    """An nginx server block routing /app/<slug> to each app's internal port."""
    blocks = []
    for r in routes:
        blocks.append(
            f"    # {r['name']} ({r['framework']})\n"
            f"    # bare path redirects to the trailing-slash app URL\n"
            f"    location = /{r['path']} {{ return 301 /{r['path']}/; }}\n"
            f"    location /{r['path']}/ {{\n"
            f"        proxy_pass http://127.0.0.1:{r['port']}/{r['path']}/;\n"
            f"        proxy_http_version 1.1;\n"
            f"        proxy_set_header Upgrade $http_upgrade;\n"
            f"        proxy_set_header Connection \"upgrade\";\n"
            f"        proxy_set_header Host $host;\n"
            f"        proxy_set_header X-Real-IP $remote_addr;\n"
            f"        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
            f"        proxy_set_header X-Forwarded-Proto $scheme;\n"
            f"        proxy_read_timeout 3600s;\n"
            f"        proxy_buffering off;\n"
            f"    }}\n"
            f"\n")
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = "".join(blocks) if blocks else \
        "    # No running deployments yet.\n\n"
    return NGINX_HEADER.format(generated=generated) + body + NGINX_FOOTER


def deploy(session: Session, deployment: Deployment, *, task_type: str = "classification") -> Deployment:
    root = Path(deployment.bundle_path)
    if not root.exists():
        deployment.status = DeploymentStatus.FAILED
        deployment.build_logs = "Bundle directory missing. Upload the app source first."
        session.add(deployment)
        session.commit()
        return deployment

    port = deployment.internal_port or _allocate_port(session)
    deployment.internal_port = port
    base_path = base_url_path(deployment.slug)
    dockerfile = ensure_scaffold(root, deployment.framework, deployment.entrypoint,
                                 port, base_path)
    logs = [f"[{datetime.now(timezone.utc):%H:%M:%S}] Bundle: {root.name}",
            f"[build] Dockerfile generated for {deployment.framework.value} on port {port}",
            f"[build] served at /{base_path} (virtual directory on main domain)"]

    driver = settings.deploy_driver
    if driver == "coolify":
        deployment = _deploy_coolify(deployment, logs, dockerfile)
    elif driver == "manifest":
        deployment.status = DeploymentStatus.DRAFT
        logs.append("[manifest] Dockerfile + compose written. Execution skipped (manifest driver).")
    else:
        deployment = _deploy_local(deployment, root, port, logs)

    deployment.build_logs = "\n".join(logs)[-16000:]
    deployment.updated_at = datetime.now(timezone.utc)
    session.add(deployment)
    session.commit()
    session.refresh(deployment)
    return deployment


def _deploy_local(deployment: Deployment, root: Path, port: int, logs: list[str]) -> Deployment:
    stop(deployment)
    venv = root / ".venv"
    py = venv / "bin" / "python"
    try:
        if not py.exists():
            logs.append("[env] creating virtualenv")
            subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True,
                           capture_output=True, timeout=180)
        req = root / "requirements.txt"
        logs.append("[env] installing requirements (this can take a minute)")

        # pip unpacks wheels through TMPDIR, which on most container images is a
        # small tmpfs. A CV app pulling torch needs ~2 GB of scratch and dies with
        # "No space left on device" long before the disk is full, so give pip a
        # build directory next to the bundle where the real space is. Cleaned up
        # afterwards so a deployment does not keep the scratch around.
        scratch = root / ".pip-tmp"
        scratch.mkdir(exist_ok=True)
        pip_env = dict(os.environ, TMPDIR=str(scratch),
                       PIP_CACHE_DIR=str(root / ".pip-cache"),
                       PIP_DISABLE_PIP_VERSION_CHECK="1")
        try:
            proc = subprocess.run([str(py), "-m", "pip", "install", "-q", "-r", str(req)],
                                  capture_output=True, text=True, timeout=1800,
                                  env=pip_env)
        finally:
            shutil.rmtree(scratch, ignore_errors=True)

        if proc.returncode != 0:
            tail = (proc.stderr or proc.stdout or "").strip()[-1500:]
            if "No space left on device" in tail:
                tail += ("\n[hint] the build ran out of scratch space. Free disk under "
                         "storage/deployments, or trim requirements.txt.")
            logs.append(f"[env] pip failed: {tail}")
            deployment.status = DeploymentStatus.FAILED
            return deployment
        logs.append("[env] dependencies ready")
    except Exception as exc:
        logs.append(f"[env] error: {exc}")
        deployment.status = DeploymentStatus.FAILED
        return deployment

    base_path = base_url_path(deployment.slug)
    env = dict(os.environ, GRADIO_SERVER_NAME="0.0.0.0", GRADIO_SERVER_PORT=str(port),
               PYTHONUNBUFFERED="1")
    if deployment.framework == AppFramework.STREAMLIT:
        cmd = [str(py), "-m", "streamlit", "run", deployment.entrypoint,
               f"--server.port={port}", "--server.address=0.0.0.0",
               f"--server.baseUrlPath={base_path}",
               "--server.headless=true", "--browser.gatherUsageStats=false"]
    else:
        env[GRADIO_ROOT_PATH_ENV] = f"/{base_path}"
        cmd = [str(py), deployment.entrypoint]

    if not _wait_for_port(port):
        logs.append(f"[run] port {port} is still held by an older process")
        deployment.status = DeploymentStatus.FAILED
        return deployment

    log_file = root / "runtime.log"
    handle = log_file.open("wb")
    proc = subprocess.Popen(cmd, cwd=str(root), stdout=handle, stderr=subprocess.STDOUT,
                            env=env, start_new_session=True)

    # Don't claim RUNNING until the app is actually serving. A Streamlit that
    # dies on a bad import or a taken port would otherwise be published to the
    # portal as a working submission.
    deadline = time.monotonic() + 90
    serving = False
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            break
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(0.5)
            if s.connect_ex(("127.0.0.1", port)) == 0:
                serving = True
                break
        time.sleep(0.5)

    if not serving:
        tail = ""
        try:
            tail = log_file.read_text(errors="replace")[-800:].strip()
        except OSError:
            pass
        logs.append(f"[run] app did not start listening on {port}"
                    + (f": {tail}" if tail else ""))
        deployment.status = DeploymentStatus.FAILED
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
        except (ProcessLookupError, PermissionError):
            pass
        return deployment

    deployment.process_pid = proc.pid
    deployment.status = DeploymentStatus.RUNNING
    deployment.url = _public_url(port, deployment.slug)
    logs.append(f"[run] pid={proc.pid} serving on {port} -> {deployment.url}")
    return deployment


def _deploy_coolify(deployment: Deployment, logs: list[str], dockerfile: str) -> Deployment:
    if not (settings.coolify_base_url and settings.coolify_token):
        logs.append("[coolify] credentials missing; falling back to manifest only.")
        deployment.status = DeploymentStatus.DRAFT
        return deployment
    headers = {"Authorization": f"Bearer {settings.coolify_token}", "Content-Type": "application/json"}
    payload = {
        "project_uuid": settings.coolify_project_uuid,
        "server_uuid": settings.coolify_server_uuid,
        "name": deployment.slug,
        "docker_compose_raw": (Path(deployment.bundle_path) / "docker-compose.yml").read_text(),
        "instant_deploy": True,
    }
    try:
        with httpx.Client(timeout=60) as client:
            resp = client.post(f"{settings.coolify_base_url.rstrip('/')}/api/v1/applications/dockercompose",
                               headers=headers, json=payload)
        if resp.status_code < 400:
            data = resp.json()
            deployment.status = DeploymentStatus.BUILDING
            deployment.url = data.get("fqdn") or data.get("url") or deployment.url
            logs.append(f"[coolify] deployment triggered: {data.get('uuid', 'ok')}")
        else:
            deployment.status = DeploymentStatus.FAILED
            logs.append(f"[coolify] API error {resp.status_code}: {resp.text[:400]}")
    except Exception as exc:
        deployment.status = DeploymentStatus.FAILED
        logs.append(f"[coolify] error: {exc}")
    return deployment


def stop(deployment: Deployment) -> None:
    """Stop the app and wait for it to actually be gone.

    Signalling and returning immediately is not enough: a redeploy starts the
    replacement within milliseconds, the old Streamlit still holds the port,
    and the new one exits with "Port 8600 is not available" while the database
    happily records RUNNING. So SIGTERM, wait, then SIGKILL, then confirm the
    port is free before anyone tries to bind it again.
    """
    pid = deployment.process_pid
    deployment.process_pid = None
    if not pid:
        return

    try:
        pgid = os.getpgid(pid)
    except (ProcessLookupError, PermissionError):
        return

    for sig in (signal.SIGTERM, signal.SIGKILL):
        try:
            os.killpg(pgid, sig)
        except (ProcessLookupError, PermissionError):
            return
        # Give it a moment to unwind; SIGKILL only if SIGTERM was ignored.
        for _ in range(30 if sig is signal.SIGTERM else 20):
            time.sleep(0.1)
            try:
                os.killpg(pgid, 0)
            except (ProcessLookupError, PermissionError):
                return


def _wait_for_port(port: int, timeout: float = 8.0) -> bool:
    """True once nothing is listening on `port`."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(0.4)
            if s.connect_ex(("127.0.0.1", port)) != 0:
                return True
        time.sleep(0.3)
    return False
